display_information:
  name: GitBook
  description: Get updates on Slack 
features:
  bot_user:
    display_name: GitBook
    always_online: false
  unfurl_domains:
    - app.gitbook.com
oauth_config:
  redirect_urls:
    - https://integrations.gitbook.com/v1/integrations/slack/
  scopes:
    bot:
      - channels:read
      - chat:write
      - links:read
      - links:write
settings:
  event_subscriptions:
    request_url: https://integrations.gitbook.com/v1/integrations/slack/events
    bot_events:
      - link_shared
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
