display_information:
  name: GitBook
features:
  bot_user:
    display_name: GitBook
    always_online: false
oauth_config:
  redirect_urls:
    - https://integrations.gitbook.com/v1/integrations/slack/
  scopes:
    bot:
      - chat:write
settings:
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
